### PR TITLE
[C] Remove the usage of duplicated setting of errno by errno = ERROR_…

### PR DESCRIPTION
**Pull request by lygstate**
…NO_MACRO

### CODE REVIEW

**Comment by tmontgomery** [comment]
We want to set the errno in these cases as we do not know what the app is doing.

**Comment by lygstate** [comment]
@tmontgomery You didn't got the idea, errno  are already setted in aeron_set_err

**Comment by tmontgomery** [comment]
I got it. But this is future proofing. If we later decide not to set errno in `aeron_set_err`, then it will break. So, no we want to set it explicitly at the API so that it won't break later.

**Comment by lygstate** [comment]
@tmontgomery So why not make a consistence decision.

**Comment by tmontgomery** [comment]
`aeron_set_err` setting errno is not valid in some cases, BTW, as the err code is not the same range as errno. So, it should be conditionally set or not set at all.

**Pull request closed without merging**
