### PR TITLE
Added generation of shared library for Aeron Client

### PR DESCRIPTION
**Pull request by agritsiuk-excelian**

### CODE REVIEW

**Comment by tmontgomery** [comment]
Broken build. Also, this is not enough to make the shared library be tested in CI nor handle everything it needs to do for all platforms.

**Comment by agritsiuk-excelian** [comment]
> Broken build. Also, this is not enough to make the shared library be tested in CI nor handle everything it needs to do for all platforms.

If I leave static library name as is (aeron_client) and make a shared one with aeron_client_shared name -- should it work?

I was able to build locally.

**Comment by tmontgomery** [comment]
Please see Travis link on this PR.

**Comment by agritsiuk-excelian** [comment]
> Please see Travis link on this PR.

Fixed

**Comment by tmontgomery** [comment]
Few more things.
* Travis CI needs to have a build where the examples link vs. the shared library for sanity checking (mentioned this above). Will require adding an option to cmake to control how to link them, and
* For completeness, Windows should have a DllMain and export the required functions.

**Comment by agritsiuk-excelian** [comment]
Will reopen PR once done

**Pull request closed without merging**
