### PR TITLE
C driver send and receive timestamps

### PR DESCRIPTION
**Pull request by mikeb01**

### CODE REVIEW

**Review by tmontgomery — APPROVED** [review]

**Comment by mjpt777** [comment]
I'm not sold on the `rx` and `receive` timestamp naming.  I wonder if there is better potentially name for `rx`.

**Comment by mikeb01** [comment]
I picked `rx` as it matches with the kernel naming for the same timestamp.  One option would be to stick with receive but use a qualifying term.  E.g. packet receive timestamp and endpoint receive timestamp.  `pkt-rcv-ts-offset` and `endpoint-rcv-ts-offset` as uri parameter names?

**Comment by mjpt777** [comment]
@mikeb01 I think that naming is getting better. How about  `media-rcv-ts-off', `aeron-rcv-ts-off`? Or some shortening of that?

**Comment by mikeb01** [comment]
` media-rcv-ts-off` is good, but I think `aeron-rcv-ts-off` too vague as the whole system is Aeron so that timestamp could be taken anywhere.  I'll change `rx-ts-offset` to media tomorrow and a further think on the other one.

**Comment by mikeb01** [comment]
I think channel works.

**Pull request merged**
