### PR TITLE
Add test to repro #709

### PR DESCRIPTION
**Pull request by Tomius**
I get the following exception in this test:
```
io.aeron.MultiDestinationSubscriptionTest > subscriptionCloseShouldAlsoCloseMediaDriverPorts STANDARD_ERROR
    io.aeron.exceptions.AeronException: channel error - Address already in use: bind (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=localhost:54325
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:165)
        at io.aeron.driver.media.ReceiveDestinationUdpTransport.openChannel(ReceiveDestinationUdpTransport.java:35)
        at io.aeron.driver.Receiver.onAddDestination(Receiver.java:173)
        at io.aeron.driver.ReceiverProxy.addDestination(ReceiverProxy.java:158)
        at io.aeron.driver.DriverConductor.onAddRcvDestination(DriverConductor.java:894)
        at io.aeron.driver.ClientCommandAdapter.onMessage(ClientCommandAdapter.java:216)
        at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:158)
        at io.aeron.driver.ClientCommandAdapter.receive(ClientCommandAdapter.java:65)
        at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:151)
        at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:283)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:461)
        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:814)
        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:785)
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:125)
        ... 12 more

io.aeron.MultiDestinationSubscriptionTest > subscriptionCloseShouldAlsoCloseMediaDriverPorts FAILED
    io.aeron.exceptions.RegistrationException: errorCodeValue=0 AeronException : channel error - Address already in use: bind (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=localhost:54325
        at io.aeron.ClientConductor.onError(ClientConductor.java:219)
        at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:108)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
        at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:63)
        at io.aeron.ClientConductor.service(ClientConductor.java:896)
        at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:945)
        at io.aeron.ClientConductor.addRcvDestination(ClientConductor.java:593)
        at io.aeron.Subscription.addDestination(Subscription.java:423)
        at io.aeron.MultiDestinationSubscriptionTest.subscriptionCloseShouldAlsoCloseMediaDriverPorts(MultiDestinationSubscriptionTest.java:469)
```

### CODE REVIEW

**Comment by tmontgomery** [comment]
Checkstyle is failing for your PR.

**Comment by tmontgomery** [comment]
Also, this test passes for me on the head fine.

You do realize that when ports are closed on some OSs that the port isn't IMMEDIATELY free'd?

**Comment by Tomius** [comment]
Yes, but the ports are left open for me for hours (on Windows 10). And the test passes if I explicitly add removeDestionation or subscribe on publicationChannelA instead of using manual control channel.

**Comment by Tomius** [comment]
Note: I actually checked with the 1.21.2 release, not master.

**Comment by tmontgomery** [comment]
I don't know what to tell you. I can see from your test that for me on MacOS, it passes every time. And I can see it is calling the transport close on the destination transport.

All on master.

**Comment by tmontgomery** [comment]
The tests do use ports that sometimes Windows will use in its ephemeral range.

**Comment by Tomius** [comment]
It happens to me on master too. Could be Windows specific then.

err

**Comment by tmontgomery** [comment]
Could be. But as Windows is supposed to free on selectNow().... which is called in the close... not much can be done.

**Comment by tmontgomery** [comment]
BTW, tested it on my Windows 10 Pro.... I do not see it.

**Comment by tmontgomery** [comment]
I would suspect that the timing difference between not calling removeDestination and calling it allows the port to be indicated by the OS as open. Why it wouldn't free the port after so long, no clue.

But as I've kinda confirmed the transport seems to be closed....

**Comment by mjpt777** [comment]
The test does fail for me on Windows 10.

**Pull request closed without merging**
