### PR TITLE
[C] Restore dynamic logging events.

### PR DESCRIPTION
**Pull request by vyazelenko**
- Restore dynamic event logging.
- Add checks if dynamic event logging is enabled.
- Use array of structs to keep track of event descriptors.

### CODE REVIEW

**Comment by mjpt777** [comment]
I think the arrays of structs is more readable.

**Comment by vyazelenko** [comment]
@mjpt777 Any blockers for this PR to be merged?

**Comment by mjpt777** [comment]
Not from me. I was waiting for the others to feedback before merging since they had the concerns.

**Comment by tmontgomery** [comment]
LGTM

**Pull request merged**
