### PR TITLE
[Java] Add RESOLVE_HOSTNAMES command to resolve hostnames into ip when needed and tests

### PR DESCRIPTION
**Pull request by lightZebra**
There is an issue when working with aeron in cloud(kubernetes for example).
Node wouldn't reconnect to cluster after went down and up with different IP but same hostname:port.
Because hostnames resolved into IP once on startup(creation) and reused most of the time.

I added new command RESOLVE_HOSTNAMES which we could send to media driver to resolve hostnames and apply only new IP.

Scenario:
1. Start 3 static nodes
2. For some reason one node went down and up with different IP but same hostname:port and data written to disk(still can't join cluster).
3. Using DriverTool CLI(or programmatically) execute "resolveHostname" command for 2 other nodes(also we could execute command for each node, result will be the same)
4. Hostnames with new IP will be updated, old IP stay as it is
5. Cluster working again with 3 nodes.

Added tests and tested using docker-compose and kubernetes.

### CODE REVIEW

**Comment by mjpt777** [comment]
This is a good start but it is incomplete. When IPs change then the canonical form for URIs will change. If they are not updated then latter adds for pubs and subs will not match with the ones registered before names are re-resolved.

**Comment by lightZebra** [comment]
Thank you for the feedback. I'm glad that I'm on the right track and will continue working on this.

**Comment by mjpt777** [comment]
This fails the build on Java 11.

https://travis-ci.org/real-logic/aeron/jobs/615559707?utm_medium=notification&utm_source=github_status

**Comment by lightZebra** [comment]
I have fixed the issue with canonical form and added tests for send and receive channels.
Unfortunately I haven't found better way to change hostname resolution on a fly than reflection.

Also, it seems like `onResolveHostnames` method should update `PublicationImage.imageConnections` because we have `InetSocketAddress` inside which will be used as a send address.
But cluster seems working even with current changes.
Am I missing something, or we don't need to update `PublicationImage.imageConnections` right now?

**Comment by lightZebra** [comment]
Did someone get a chance to look at latest changes? Do we need something more to merge this?

**Comment by tmontgomery** [comment]
This is not the direction we want to go with supporting Kubernetes and cloud for re-resolution.

We have a more holistic approach in mind that we've been looking at that is automatic and not necessarily tied to the underlying name resolution.

However, if OK, let's keep this open for now as some of this might be very useful.

**Comment by lightZebra** [comment]
Last update, might be useful
Added automatic hostname resolution when `timeNs > statusMessageDeadlineNs` with delay between resolutions. Removed resolve command.

I hope this version somehow correlate with your approach. I see latest solution as good enough, at least good point to start from, so people could start using it in near time.

Let me know is it good enough for you? 
Anyway you could leave it open if you need, it's OK for me.
If you don't have any solution right now and don't have plans to add it soon then maybe we could use this one for now, is it possible?

**Comment by mjpt777** [comment]
A better approach has been implemented in Aeron for re-resolution.

**Pull request closed without merging**
