### PR TITLE
Change the round-robin mechanism of Subscription's poll methods

### PR DESCRIPTION
**Pull request by denizevrenci**
To be able to continue from the next `Image` in subsequent calls.

### CODE REVIEW

**Comment by mjpt777** [comment]
What is the goal to be achieved with the change?

**Comment by denizevrenci** [comment]
If the number of fragments in earlier images in the list is larger than `fragmentLimit`, processing the fragments in the last image in the list takes `N` calls to `poll()` as we lose the position (`i`) in the list. After this change, the subsequent calls "remember" the last processed position (`i`). So `poll()` can iterate the list faster.

With a small number of images, the effect is probably unnoticeable. And if each image has more than `fragmentLimit` number of unprocessed fragments, this change does not affect the behaviour.

It is a micro-optimization that will probably affect very few use cases. If you think it does not serve a purpose, please feel free to close this PR.

**Comment by mjpt777** [comment]
This broke the build and so reverted it.

**Comment by denizevrenci** [comment]
Sorry to pollute the commit history. Seems like cluster tests are failing with index out of bounds errors. I'll investigate and update the PR.

**Pull request merged**
