### PR TITLE
Add background snapshots

### PR DESCRIPTION
**Pull request by mikeb01**
- Add control toggle option BACKGROUND_SNAPSHOTS
- Leader selects a follower to take the snapshot
- Non-snapshotting members notice the snapshot entry in the log and will try to replicate the snapshot locally.

### CODE REVIEW

**Comment by vachb** [comment]
thanks for this Mike, perfect timing! 
quick question : if we assume a service is taking big snapshots (lets say 10GB) when a snapshot is taken and it starts to replicate is it possible that it will saturate the network bandwidth? is there some sort of priority for snapshots so that they do not aggressively use bandwidth, for example if network is saturated one would prefer the snapshot to have much less priority than the messages that are getting replicated around...

**Comment by mikeb01** [comment]
> if we assume a service is taking big snapshots (lets say 10GB) when a snapshot is taken and it starts to replicate is it possible that it will saturate the network bandwidth?

These are sorts of questions we have to work through and one of the reasons why this needs further understanding and review.  Options for this specific case could include using congestion control on the topic used for replicating the snapshots.

There are other concerns as well, like the effects on flow control while the follower is replicating.

**Comment by dave5595** [comment]
@mikeb01 Hi Mike, out of curiosity, why was this PR not merged? Is this feature only available on Aeron Premium?

**Comment by mjpt777** [comment]
@dave5595 Background snapshots are one of the features available in Aeron premium. There are numerous issues with doing background snapshots in the OSS version and a better implementation was possible using our standby nodes in Aeron Premium.

**Pull request closed without merging**
