### PR TITLE
Refactor image ownership

### PR DESCRIPTION
**Pull request by denizevrenci**
Follow-up to https://github.com/real-logic/aeron/pull/631.

### CODE REVIEW

**Comment by denizevrenci** [comment]
https://travis-ci.org/real-logic/aeron/jobs/500250411
Race condition?

**Comment by tmontgomery** [comment]
Those tests are fairly sensitive to starvation or resources. Just by their very nature.

**Comment by mjpt777** [comment]
@tmontgomery Any view on this?

**Comment by tmontgomery** [comment]
Haven't reviewed it yet. But will try to get time to soon.

**Comment by tmontgomery** [comment]
Sorry for the delay on this. I think we want to hold off on this. I want to do a more extensive adjustment to the Image handling and this only gets in the way.

**Comment by tmontgomery** [comment]
I've done an initial pass at what I wanted in 0d484ec . I used some of the techniques in this PR. Any comments you have, @denizevrenci would be most welcome.

**Pull request closed without merging**
