### PR TITLE
Use StopPosition as terminating condition for snapshot transfer

### PR DESCRIPTION
**Pull request by JPWatson**
(Currently using synchronous call to get stop position, looking at making that async)

### CODE REVIEW

**Comment by tmontgomery** [comment]
What about putting the snapshot length in the backup response message?

**Comment by JPWatson** [comment]
Think that would probably require a breaking change to the recording.log to include the stop position.

**Comment by mjpt777** [comment]
Also looking this up would cause a pause to the consensus module. Use replicate could be a good compromise.

**Comment by tmontgomery** [comment]
The snapshot length is a consequence of loading or recording a snapshot. So, doesn't need to be in the recording log. Nor does it require it also be queried when responding.... as it can be saved when taking or loading a snapshot.

The only incompatibility is in the Query response messages. And as if you are running ClusterBackup then you need to be on the same version. No reason not to be current.

**Comment by tmontgomery** [comment]
BTW, I've now confirmed this also happens with Dynamic Join as the same logic error is there.

**Comment by tmontgomery** [comment]
It is hard to tell from the diff as so much is moved around what is actually added here.

A blocking archive query will not play well with the activity checking that has been added.

**Comment by JPWatson** [comment]
In that case, there's also a blocking call to stopRecording.

**Comment by tmontgomery** [comment]
It's a local call to backupArchive and not a network call. We tend to not treat them as non-blocking.... even though we should.

**Comment by JPWatson** [comment]
Fair enough.

**Comment by tmontgomery** [comment]
I have an async version stashed. Don't have time to get it in today and port to DynamicJoin and also to add a test with a larger snapshot before release.

But, will do so tonight and/or tomorrow.

**Comment by tmontgomery** [comment]
With 6d4d064f43485660f276d51a202f32910606a075 , this is no longer needed.

**Pull request closed without merging**
