### PR TITLE
Specify charset explicitly for Admin Endpoint

### PR DESCRIPTION
**Pull request by JPWatson**

### CODE REVIEW

**Comment by mjpt777** [comment]
If we do specify I feel it would be better to restrict to US-ASCII.

**Comment by tmontgomery** [comment]
This is changing. Drastically. It'll be the same format as ClusterMember.parse. Including the memberId.

**Comment by tmontgomery** [comment]
I've pushed the format change. I agree with @mjpt777 , the format used should be US-ASCII.

**Comment by JPWatson** [comment]
Done

**Pull request merged**
