### PR TITLE
[C] '+' and ':' are not valid win32 path symbol. replace them with '-'

### PR DESCRIPTION
**Pull request by lygstate**
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

**Comment by lygstate** [comment]
Updated with exist style

**Comment by tmontgomery** [comment]
This needs to be defined for Windows specifically.

**Comment by lygstate** [comment]
I didn't do it for consistence across platform, and also the Java Version use the same schema.

**Comment by tmontgomery** [comment]
Ah. Very good. I had missed that. Thanks!

**Pull request merged**
