### PR TITLE
[C] make sure the cnc.dat have valid file length before init mpsc

### PR DESCRIPTION
**Pull request by lygstate**
Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

**Comment by tmontgomery** [comment]
This is a dupe of #926 . Close one or the other.

**Comment by mjpt777** [comment]
@lygstate  Do you have evidence, or some failing test, that illustrates how a mapped file is not either zero or the correct length?

**Comment by lygstate** [comment]
@mjpt777 Easy to reproduce for the Java Client with C Media driver, just enable the Windows System  C Media Driver test, then the error would happen. That's way I spent so much time to fix it. I need keep the CI clean.

**Comment by tmontgomery** [comment]
Again, C windows driver is not supported and may not work. Does this happen on Windows with Java and Java client?

**Comment by lygstate** [comment]
The C media driver are working fine for me now, after fixing those issues, especially #932 and #933 (These two issue not only happens on Windows, but on all platform) . Java media driver with Java client didn't have any problem.

**Pull request closed without merging**
