### PR TITLE
converting AeronStat into a util class that can be used to print data to a stream

### PR DESCRIPTION
**Pull request by kirtiteja**
Hi,
I made an attempt at resolving this enhancement https://github.com/real-logic/Aeron/issues/167.
Please review and let me know of any changes required.

Thanks,

### CODE REVIEW

**Comment by mjpt777** [comment]
Please run the full build with PRs. The PR failed checkstyle.

Are you aware that the lambdas are capturing and will allocated on each call to the methods?

**Comment by kirtiteja** [comment]
Ah damn, i did run the build with checkstyle, not sure where I went wrong, will verify that now. Sorry for the trouble. I am aware lambdas will be allocated on each call but it wasnt my intention to make it garbage free considering the streams and formatting of output. Encoding into bytebuffer is more of an after thought and one that benefits being garbage free. Will work on it and submit it later. Please let me know if have any inputs or thoughts on using ByteBuffer vs UnsafeBuffer? or regarding data being written or format of encoding?

**Comment by mjpt777** [comment]
Let me check why the checkstyle passed for you. I updated it recently. For example, we should have caught the curly bracket misalignment and 4 space indentation.

**Comment by mjpt777** [comment]
My bad. My IDE settings are not all reflected in checkstyle config.

**Comment by kirtiteja** [comment]
No worries, happens to me all the time .

**Comment by mjpt777** [comment]
Sorry for that :-/

**Comment by mjpt777** [comment]
You also uncovered a little bug in Checkstyle: https://github.com/checkstyle/checkstyle/issues/2818

**Pull request merged**
