### PR TITLE
[C] Add test for reproducing issue #1313

### PR DESCRIPTION
**Pull request by alokpr**

### CODE REVIEW

**Comment by alokpr** [comment]
```
$ pubsub_test --gtest_filter=PubSubTest.OneToOne
Running main() from gmock_main.cc
Note: Google Test filter = PubSubTest.OneToOne
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PubSubTest
[ RUN      ] PubSubTest.OneToOne
[       OK ] PubSubTest.OneToOne (86 ms)
[----------] 1 test from PubSubTest (86 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (86 ms total)
[  PASSED  ] 1 test.


$ pubsub_test --gtest_filter=PubSubTest.OneToMany
Running main() from gmock_main.cc
Note: Google Test filter = PubSubTest.OneToMany
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from PubSubTest
[ RUN      ] PubSubTest.OneToMany
[       OK ] PubSubTest.OneToMany (87 ms)
[----------] 1 test from PubSubTest (87 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (87 ms total)
[  PASSED  ] 1 test.

=================================================================
==27429==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f7380ee3d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x7f7380a3058d in aeron_alloc /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_alloc.c:53
    #2 0x7f7380a871fa in aeron_image_create /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_image.c:74
    #3 0x7f7380a61437 in aeron_client_conductor_on_available_image /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:2184
    #4 0x7f7380a66d71 in aeron_client_conductor_on_driver_response /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:282
    #5 0x7f73809f2d62 in aeron_broadcast_receiver_receive /home/alok/src/aeron-fork/aeron-client/src/main/c/concurrent/aeron_broadcast_receiver.c:100
    #6 0x7f7380a543b5 in aeron_client_conductor_do_work /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:569
    #7 0x7f7380a2dfe4 in agent_main /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_agent.c:407
    #8 0x7f737fcd06da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x7f7380ee3d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x7f7380a3058d in aeron_alloc /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_alloc.c:53
    #2 0x7f7380a87240 in aeron_image_create /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_image.c:75
    #3 0x7f7380a61437 in aeron_client_conductor_on_available_image /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:2184
    #4 0x7f7380a66d71 in aeron_client_conductor_on_driver_response /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:282
    #5 0x7f73809f2d62 in aeron_broadcast_receiver_receive /home/alok/src/aeron-fork/aeron-client/src/main/c/concurrent/aeron_broadcast_receiver.c:100
    #6 0x7f7380a543b5 in aeron_client_conductor_do_work /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_client_conductor.c:569
    #7 0x7f7380a2dfe4 in agent_main /home/alok/src/aeron-fork/aeron-client/src/main/c/aeron_agent.c:407
    #8 0x7f737fcd06da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

SUMMARY: AddressSanitizer: 154 byte(s) leaked in 2 allocation(s).
```

**Comment by tmontgomery** [comment]
Something to be aware of is `aeron_subscription_close` is asynchronous. And thus, it is hard to be sure that if you don't wait that the image is being leaked due to client close cleanup or because of lingering, etc. It is most likely still being leaked, however. But the where is a little more complex to figure out adn thus impact is not easy to assess.

**Comment by mikeb01** [comment]
The leak caused by the subscription not being closed completely before the test exits.  Changing the test to wait until the subscription is closed fixes the sanitizer errors.

```
diff --git a/aeron-client/src/test/c/aeron_pubsub_test.cpp b/aeron-client/src/test/c/aeron_pubsub_test.cpp
index 2076e7a0a..0c77984b8 100644
--- a/aeron-client/src/test/c/aeron_pubsub_test.cpp
+++ b/aeron-client/src/test/c/aeron_pubsub_test.cpp
@@ -6,6 +6,11 @@ constexpr char kChannel[] = "aeron:ipc";
 constexpr int kStream = 100;
 constexpr uint8_t kMessage = 42;
 
+static void closeNotification(void *clientd) {
+  bool *closed = static_cast<bool *>(clientd);
+  *closed = true;
+}
+
 class BlockingPublisher {
  public:
   ~BlockingPublisher() {
@@ -50,7 +55,13 @@ class BlockingSubscriber {
   ~BlockingSubscriber() {
     assert(!pending_handler);
     if (fragment_assembler) aeron_fragment_assembler_delete(fragment_assembler);
-    if (subscription) aeron_subscription_close(subscription, nullptr, nullptr);
+    if (subscription) {
+      bool closed = false;
+      aeron_subscription_close(subscription, closeNotification, &closed);
+      while (!closed) {
+        sched_yield();
+      }
+    }
   }
 
   int Connect(aeron_t* client, const char* uri, int stream_id) {
```

**Comment by alokpr** [comment]
@mikeb01 Hmm.. I expected `aeron_close` or `aeron_context_close` to synchronously cleanup at least closed (or marked closed) subscriptions. Is that not feasible? I find the current behavior a bit inconvenient to use and surprising.

**Comment by alokpr** [comment]
I suspect that this might be a problem for the cpp-wrapper too since it does not provide a mechanism for clients to wait:
https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp_wrapper/Subscription.h#L98

Do clients also need to wait for publication to close to avoid memory leaks?

**Comment by tmontgomery** [comment]
There is some cleanup for cases where the client closes. However, I believe the case here is that the image is in a state of ownership being in question when it closes due to the close being in the command queue. Making it clean up, in this case, is probably something we can look at when we have time (is a low priority).

In any event, applications should wait for closes to complete for quite a few reasons. So, it is best practice anyway.

**Comment by mikeb01** [comment]
@alokpr It can be a bit annoying in the tests as they can exit before close operations are complete.  You can work around this by tracking the subsciber's counters or using the invoker approach to control the driver's poll functions (cpp_wrapper/SystemTest.cpp does this).

**Pull request closed without merging**
