### PR TITLE
Add a single place to register counter type IDs for Java and C.

### LINKED ISSUE #747: Counters listing and type ids
Create a file in each module listing counters and specified ranges.

0-99: for client & driver counters
100-199: for archive counters
200-299: for cluster counters

Consider outlining metadata and dissectors.

### PR DESCRIPTION
**Pull request by vyazelenko**
Fixes #747

### CODE REVIEW

**Comment by mjpt777** [comment]
Now needs Archive and Cluster to be covered.

**Comment by vyazelenko** [comment]
@mjpt777 The idea is to add those to the very same file. There are even comments added there for Archive and Cluster counters. However I haven't found a single Archive/Cluster counter creation, i.e. the `CountersManager` API is not used from those modules?!

**Comment by mjpt777** [comment]
Those modules use the Aeron client API to add counters.

**Comment by vyazelenko** [comment]
Will pick those up and create another PR. ;)

**Pull request merged**
