### PR TITLE
Various cleanup of C++ client

### PR DESCRIPTION
**Pull request by denizevrenci**
And two new features:
* Make Image movable without a copy.
* Add an accessor to Context for media driver timeout.

### CODE REVIEW

**Comment by mjpt777** [comment]
A lot of this looks good. However removing the `Context::conclude()` changes the semantics for how contexts are used by convention. This will expand with archive and cluster being integrated.

**Comment by tmontgomery** [comment]
Couple/Few things.

* not sure about asserting on clz value of 0. I know why. Just not comfortable with it instead of a guard.
* `Context.conclude` is needed in general. We could get away with it, but better to keep it.
* I've tried various things with Images. Copying vs. Moving, etc. This is fine. But I think in general, we will eventually need to move to be compatible with how Java does it instead of trying to be local with the array. In other words, Image should be a standalone object. And the array in Subscription should be an array of pointers to Images.

**Comment by denizevrenci** [comment]
@mjpt777 I have put back `conclude()` and just changed the initializers to defaults instead of nulls.

@tmontgomery What kind of guard do you have in mind instead of assertions? To me, it looked like passing zero to `clz` and `ctz` is a programming error that cannot be handled at runtime.

I suppose the standalone Image can also be moved, so the addition of move semantics here would not have to be retracted later.

**Comment by tmontgomery** [comment]
I think a move for a reference doesn't make as much sense. But, in general, we can take this and then deal with that when it is needed.

The guard I was thinking of would be a return of the bit size as Java does.

**Pull request merged**
