### PR TITLE
[C++] Remove original registration ID from ExclusivePublication.

### PR DESCRIPTION
**Pull request by denizevrenci**
As exclusive publications are guaranteed to be original.

### CODE REVIEW

**Comment by mjpt777** [comment]
It is best leaving this in place as the publication API can be used interchangeable. What is the rationale for removing it?

**Comment by denizevrenci** [comment]
Just code cleanup and maybe very tiny perf gain. I kept the public API fully compatible. Though, I am not sure if conductor's `onNewExclusivePublication` callback is used by someone.

**Comment by denizevrenci** [comment]
Also wanted to confirm this statement.
> As exclusive publications are guaranteed to be original.

**Comment by mjpt777** [comment]
Exclusive publications will always be original. 

The change I'm OK with except for the change to the `onNewExclusivePublication` callback which is breaking. Maybe @tmontgomery has a view on the value of the callbacks for publications?

**Comment by tmontgomery** [comment]
Is it possible to keep the same callback and just not save the original registration ID?

**Comment by denizevrenci** [comment]
I've reverted the change on `onNewExclusivePublication` leaving the constructor of `ExclusivePublication` unchanged from the initial commit.

**Comment by mjpt777** [comment]
The test does not compile.

**Comment by denizevrenci** [comment]
I had reverted the call to the `ExclusivePublisher` constructor in the test. That has been fixed.

**Pull request merged**
