### PR TITLE
[Java] Add @SlowClusterTest annotation to allow excluding of clusteri…

### PR DESCRIPTION
**Pull request by mikeb01**
…ng tests without disabling them.

### CODE REVIEW

**Comment by mjpt777** [comment]
Slow tests are more than cluster. Annotation would be better in `aeron-client`.

**Comment by mikeb01** [comment]
I'd want to avoid putting the test annotation in aeron-client/main and sharing a dependency on another modules test is awkward (but possible).  Would it make more sense to have an aeron-test-util (or similar) module that could hold this and some of the other TestUtil classes that is only imported as a `testImplementation` dependency.

The much simpler implementation would be to not define our own annotation and just put `@Tag("slow")` directly on the test.

**Comment by vyazelenko** [comment]
@mikeb01 I like the idea of having `aeron-test-common` module. We shouldn't duplicate test code in each module.

**Comment by mjpt777** [comment]
We could have a test package in Agrona and this may be easier to share.

**Comment by tmontgomery** [comment]
Test package in Agrona sounds good to me. Have needed that for a while.

**Pull request closed without merging**
